/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.3 on Mon Sep 22 18:00:47 2014
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of QScintilla.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQsci.h"

#line 29 "sip/qscilexercpp.sip"
#include <Qsci/qscilexercpp.h>
#line 34 "./sipQsciQsciLexerCPP.cpp"

#line 34 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qobject.sip"
#include <qobject.h>
#line 38 "./sipQsciQsciLexerCPP.cpp"
#line 31 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qsettings.sip"
#include <qsettings.h>
#line 41 "./sipQsciQsciLexerCPP.cpp"
#line 36 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qstring.sip"
#include <qstring.h>
#line 44 "./sipQsciQsciLexerCPP.cpp"
#line 35 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtGui/qcolor.sip"
#include <qcolor.h>
#line 47 "./sipQsciQsciLexerCPP.cpp"
#line 35 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtGui/qfont.sip"
#include <qfont.h>
#line 50 "./sipQsciQsciLexerCPP.cpp"
#line 29 "sip/qsciabstractapis.sip"
#include <Qsci/qsciabstractapis.h>
#line 53 "./sipQsciQsciLexerCPP.cpp"
#line 29 "sip/qsciscintilla.sip"
#include <Qsci/qsciscintilla.h>
#line 56 "./sipQsciQsciLexerCPP.cpp"
#line 31 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 59 "./sipQsciQsciLexerCPP.cpp"
#line 355 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 62 "./sipQsciQsciLexerCPP.cpp"
#line 338 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 65 "./sipQsciQsciLexerCPP.cpp"
#line 274 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qvariant.sip"
#include <qvariant.h>
#line 68 "./sipQsciQsciLexerCPP.cpp"
#line 33 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 71 "./sipQsciQsciLexerCPP.cpp"
#line 37 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 74 "./sipQsciQsciLexerCPP.cpp"
#line 35 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 77 "./sipQsciQsciLexerCPP.cpp"
#line 120 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 80 "./sipQsciQsciLexerCPP.cpp"
#line 31 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qthread.sip"
#include <qthread.h>
#line 83 "./sipQsciQsciLexerCPP.cpp"
#line 35 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qregexp.sip"
#include <qregexp.h>
#line 86 "./sipQsciQsciLexerCPP.cpp"
#line 31 "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 89 "./sipQsciQsciLexerCPP.cpp"


class sipQsciLexerCPP : public QsciLexerCPP
{
public:
    sipQsciLexerCPP(QObject*,bool);
    virtual ~sipQsciLexerCPP();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void disconnectNotify(const char*);
    void connectNotify(const char*);
    void customEvent(QEvent*);
    void childEvent(QChildEvent*);
    void timerEvent(QTimerEvent*);
    bool eventFilter(QObject*,QEvent*);
    bool event(QEvent*);
    bool writeProperties(QSettings&,const QString&) const;
    bool readProperties(QSettings&,const QString&);
    void setPaper(const QColor&,int);
    void setFont(const QFont&,int);
    void setEolFill(bool,int);
    void setColor(const QColor&,int);
    void setAutoIndentStyle(int);
    const char* wordCharacters() const;
    int styleBitsNeeded() const;
    void refreshProperties();
    QColor defaultPaper(int) const;
    QFont defaultFont(int) const;
    bool defaultEolFill(int) const;
    QColor defaultColor(int) const;
    QColor paper(int) const;
    QString description(int) const;
    const char* keywords(int) const;
    QFont font(int) const;
    bool eolFill(int) const;
    QColor color(int) const;
    int lexerId() const;
    const char* lexer() const;
    const char* language() const;
    void setStylePreprocessor(bool);
    void setFoldPreprocessor(bool);
    void setFoldCompact(bool);
    void setFoldComments(bool);
    void setFoldAtElse(bool);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQsciLexerCPP(const sipQsciLexerCPP &);
    sipQsciLexerCPP &operator = (const sipQsciLexerCPP &);

    char sipPyMethods[35];
};

sipQsciLexerCPP::sipQsciLexerCPP(QObject*a0,bool a1): QsciLexerCPP(a0,a1), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQsciLexerCPP::~sipQsciLexerCPP()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQsciLexerCPP::metaObject() const
{
    return sip_Qsci_qt_metaobject(sipPySelf,sipType_QsciLexerCPP);
}

int sipQsciLexerCPP::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QsciLexerCPP::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_Qsci_qt_metacall(sipPySelf,sipType_QsciLexerCPP,_c,_id,_a);

    return _id;
}

void *sipQsciLexerCPP::qt_metacast(const char *_clname)
{
    return (sip_Qsci_qt_metacast(sipPySelf, sipType_QsciLexerCPP, _clname)) ? this : QsciLexerCPP::qt_metacast(_clname);
}

void sipQsciLexerCPP::disconnectNotify(const char*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
        QsciLexerCPP::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const char*);

    ((sipVH_QtCore_24)(sipModuleAPI_Qsci_QtCore->em_virthandlers[24]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQsciLexerCPP::connectNotify(const char*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
        QsciLexerCPP::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const char*);

    ((sipVH_QtCore_24)(sipModuleAPI_Qsci_QtCore->em_virthandlers[24]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQsciLexerCPP::customEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
        QsciLexerCPP::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_17)(sipModuleAPI_Qsci_QtCore->em_virthandlers[17]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQsciLexerCPP::childEvent(QChildEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
        QsciLexerCPP::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QChildEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_Qsci_QtCore->em_virthandlers[25]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQsciLexerCPP::timerEvent(QTimerEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
        QsciLexerCPP::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QTimerEvent*);

    ((sipVH_QtCore_9)(sipModuleAPI_Qsci_QtCore->em_virthandlers[9]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

bool sipQsciLexerCPP::eventFilter(QObject*a0,QEvent*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return QsciLexerCPP::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_18)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QObject*,QEvent*);

    return ((sipVH_QtCore_18)(sipModuleAPI_Qsci_QtCore->em_virthandlers[18]))(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

bool sipQsciLexerCPP::event(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return QsciLexerCPP::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    return ((sipVH_QtCore_5)(sipModuleAPI_Qsci_QtCore->em_virthandlers[5]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

bool sipQsciLexerCPP::writeProperties(QSettings& a0,const QString& a1) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[7]),sipPySelf,NULL,sipName_writeProperties);

    if (!sipMeth)
        return QsciLexerCPP::writeProperties(a0,a1);

    extern bool sipVH_Qsci_7(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QSettings&,const QString&);

    return sipVH_Qsci_7(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

bool sipQsciLexerCPP::readProperties(QSettings& a0,const QString& a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[8],sipPySelf,NULL,sipName_readProperties);

    if (!sipMeth)
        return QsciLexerCPP::readProperties(a0,a1);

    extern bool sipVH_Qsci_7(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QSettings&,const QString&);

    return sipVH_Qsci_7(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

void sipQsciLexerCPP::setPaper(const QColor& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[9],sipPySelf,NULL,sipName_setPaper);

    if (!sipMeth)
    {
        QsciLexerCPP::setPaper(a0,a1);
        return;
    }

    extern void sipVH_Qsci_8(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QColor&,int);

    sipVH_Qsci_8(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

void sipQsciLexerCPP::setFont(const QFont& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[10],sipPySelf,NULL,sipName_setFont);

    if (!sipMeth)
    {
        QsciLexerCPP::setFont(a0,a1);
        return;
    }

    extern void sipVH_Qsci_9(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QFont&,int);

    sipVH_Qsci_9(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

void sipQsciLexerCPP::setEolFill(bool a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[11],sipPySelf,NULL,sipName_setEolFill);

    if (!sipMeth)
    {
        QsciLexerCPP::setEolFill(a0,a1);
        return;
    }

    extern void sipVH_Qsci_10(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool,int);

    sipVH_Qsci_10(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

void sipQsciLexerCPP::setColor(const QColor& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[12],sipPySelf,NULL,sipName_setColor);

    if (!sipMeth)
    {
        QsciLexerCPP::setColor(a0,a1);
        return;
    }

    extern void sipVH_Qsci_8(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QColor&,int);

    sipVH_Qsci_8(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

void sipQsciLexerCPP::setAutoIndentStyle(int a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[13],sipPySelf,NULL,sipName_setAutoIndentStyle);

    if (!sipMeth)
    {
        QsciLexerCPP::setAutoIndentStyle(a0);
        return;
    }

    typedef void (*sipVH_QtCore_4)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    ((sipVH_QtCore_4)(sipModuleAPI_Qsci_QtCore->em_virthandlers[4]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

const char* sipQsciLexerCPP::wordCharacters() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[14]),sipPySelf,NULL,sipName_wordCharacters);

    if (!sipMeth)
        return QsciLexerCPP::wordCharacters();

    extern const char* sipVH_Qsci_11(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_Qsci_11(sipGILState, 0, sipPySelf, sipMeth, -126);
}

int sipQsciLexerCPP::styleBitsNeeded() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[15]),sipPySelf,NULL,sipName_styleBitsNeeded);

    if (!sipMeth)
        return QsciLexerCPP::styleBitsNeeded();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_Qsci_QtCore->em_virthandlers[6]))(sipGILState, 0, sipPySelf, sipMeth);
}

void sipQsciLexerCPP::refreshProperties()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[16],sipPySelf,NULL,sipName_refreshProperties);

    if (!sipMeth)
    {
        QsciLexerCPP::refreshProperties();
        return;
    }

    typedef void (*sipVH_QtCore_11)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    ((sipVH_QtCore_11)(sipModuleAPI_Qsci_QtCore->em_virthandlers[11]))(sipGILState, 0, sipPySelf, sipMeth);
}

QColor sipQsciLexerCPP::defaultPaper(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[17]),sipPySelf,NULL,sipName_defaultPaper);

    if (!sipMeth)
        return QsciLexerCPP::defaultPaper(a0);

    extern QColor sipVH_Qsci_12(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_Qsci_12(sipGILState, 0, sipPySelf, sipMeth, a0);
}

QFont sipQsciLexerCPP::defaultFont(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[18]),sipPySelf,NULL,sipName_defaultFont);

    if (!sipMeth)
        return QsciLexerCPP::defaultFont(a0);

    extern QFont sipVH_Qsci_13(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_Qsci_13(sipGILState, 0, sipPySelf, sipMeth, a0);
}

bool sipQsciLexerCPP::defaultEolFill(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[19]),sipPySelf,NULL,sipName_defaultEolFill);

    if (!sipMeth)
        return QsciLexerCPP::defaultEolFill(a0);

    typedef bool (*sipVH_QtCore_23)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return ((sipVH_QtCore_23)(sipModuleAPI_Qsci_QtCore->em_virthandlers[23]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

QColor sipQsciLexerCPP::defaultColor(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[20]),sipPySelf,NULL,sipName_defaultColor);

    if (!sipMeth)
        return QsciLexerCPP::defaultColor(a0);

    extern QColor sipVH_Qsci_12(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_Qsci_12(sipGILState, 0, sipPySelf, sipMeth, a0);
}

QColor sipQsciLexerCPP::paper(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[21]),sipPySelf,NULL,sipName_paper);

    if (!sipMeth)
        return QsciLexerCPP::paper(a0);

    extern QColor sipVH_Qsci_12(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_Qsci_12(sipGILState, 0, sipPySelf, sipMeth, a0);
}

QString sipQsciLexerCPP::description(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[22]),sipPySelf,NULL,sipName_description);

    if (!sipMeth)
        return QsciLexerCPP::description(a0);

    typedef QString (*sipVH_QtGui_111)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return ((sipVH_QtGui_111)(sipModuleAPI_Qsci_QtGui->em_virthandlers[111]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

const char* sipQsciLexerCPP::keywords(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[23]),sipPySelf,NULL,sipName_keywords);

    if (!sipMeth)
        return QsciLexerCPP::keywords(a0);

    typedef const char* (*sipVH_QtGui_150)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int, int);

    return ((sipVH_QtGui_150)(sipModuleAPI_Qsci_QtGui->em_virthandlers[150]))(sipGILState, 0, sipPySelf, sipMeth, a0, -127);
}

QFont sipQsciLexerCPP::font(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[24]),sipPySelf,NULL,sipName_font);

    if (!sipMeth)
        return QsciLexerCPP::font(a0);

    extern QFont sipVH_Qsci_13(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_Qsci_13(sipGILState, 0, sipPySelf, sipMeth, a0);
}

bool sipQsciLexerCPP::eolFill(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[25]),sipPySelf,NULL,sipName_eolFill);

    if (!sipMeth)
        return QsciLexerCPP::eolFill(a0);

    typedef bool (*sipVH_QtCore_23)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return ((sipVH_QtCore_23)(sipModuleAPI_Qsci_QtCore->em_virthandlers[23]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

QColor sipQsciLexerCPP::color(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[26]),sipPySelf,NULL,sipName_color);

    if (!sipMeth)
        return QsciLexerCPP::color(a0);

    extern QColor sipVH_Qsci_12(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_Qsci_12(sipGILState, 0, sipPySelf, sipMeth, a0);
}

int sipQsciLexerCPP::lexerId() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[27]),sipPySelf,NULL,sipName_lexerId);

    if (!sipMeth)
        return QsciLexerCPP::lexerId();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_Qsci_QtCore->em_virthandlers[6]))(sipGILState, 0, sipPySelf, sipMeth);
}

const char* sipQsciLexerCPP::lexer() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[28]),sipPySelf,NULL,sipName_lexer);

    if (!sipMeth)
        return QsciLexerCPP::lexer();

    extern const char* sipVH_Qsci_11(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_Qsci_11(sipGILState, 0, sipPySelf, sipMeth, -128);
}

const char* sipQsciLexerCPP::language() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[29]),sipPySelf,NULL,sipName_language);

    if (!sipMeth)
        return QsciLexerCPP::language();

    extern const char* sipVH_Qsci_11(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_Qsci_11(sipGILState, 0, sipPySelf, sipMeth, -129);
}

void sipQsciLexerCPP::setStylePreprocessor(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[30],sipPySelf,NULL,sipName_setStylePreprocessor);

    if (!sipMeth)
    {
        QsciLexerCPP::setStylePreprocessor(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQsciLexerCPP::setFoldPreprocessor(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[31],sipPySelf,NULL,sipName_setFoldPreprocessor);

    if (!sipMeth)
    {
        QsciLexerCPP::setFoldPreprocessor(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQsciLexerCPP::setFoldCompact(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[32],sipPySelf,NULL,sipName_setFoldCompact);

    if (!sipMeth)
    {
        QsciLexerCPP::setFoldCompact(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQsciLexerCPP::setFoldComments(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[33],sipPySelf,NULL,sipName_setFoldComments);

    if (!sipMeth)
    {
        QsciLexerCPP::setFoldComments(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQsciLexerCPP::setFoldAtElse(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[34],sipPySelf,NULL,sipName_setFoldAtElse);

    if (!sipMeth)
    {
        QsciLexerCPP::setFoldAtElse(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}


PyDoc_STRVAR(doc_QsciLexerCPP_language, "QsciLexerCPP.language() -> str");

extern "C" {static PyObject *meth_QsciLexerCPP_language(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_language(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            const char*sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerCPP::language() : sipCpp->language());

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_language, doc_QsciLexerCPP_language);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_lexer, "QsciLexerCPP.lexer() -> str");

extern "C" {static PyObject *meth_QsciLexerCPP_lexer(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_lexer(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            const char*sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerCPP::lexer() : sipCpp->lexer());

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_lexer, doc_QsciLexerCPP_lexer);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_defaultColor, "QsciLexerCPP.defaultColor(int) -> QColor");

extern "C" {static PyObject *meth_QsciLexerCPP_defaultColor(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_defaultColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            QColor*sipRes;

            sipRes = new QColor((sipSelfWasArg ? sipCpp->QsciLexerCPP::defaultColor(a0) : sipCpp->defaultColor(a0)));

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_defaultColor, doc_QsciLexerCPP_defaultColor);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_defaultEolFill, "QsciLexerCPP.defaultEolFill(int) -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_defaultEolFill(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_defaultEolFill(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerCPP::defaultEolFill(a0) : sipCpp->defaultEolFill(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_defaultEolFill, doc_QsciLexerCPP_defaultEolFill);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_defaultFont, "QsciLexerCPP.defaultFont(int) -> QFont");

extern "C" {static PyObject *meth_QsciLexerCPP_defaultFont(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_defaultFont(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            QFont*sipRes;

            sipRes = new QFont((sipSelfWasArg ? sipCpp->QsciLexerCPP::defaultFont(a0) : sipCpp->defaultFont(a0)));

            return sipConvertFromNewType(sipRes,sipType_QFont,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_defaultFont, doc_QsciLexerCPP_defaultFont);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_defaultPaper, "QsciLexerCPP.defaultPaper(int) -> QColor");

extern "C" {static PyObject *meth_QsciLexerCPP_defaultPaper(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_defaultPaper(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            QColor*sipRes;

            sipRes = new QColor((sipSelfWasArg ? sipCpp->QsciLexerCPP::defaultPaper(a0) : sipCpp->defaultPaper(a0)));

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_defaultPaper, doc_QsciLexerCPP_defaultPaper);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_keywords, "QsciLexerCPP.keywords(int) -> str");

extern "C" {static PyObject *meth_QsciLexerCPP_keywords(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_keywords(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            const char*sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerCPP::keywords(a0) : sipCpp->keywords(a0));

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_keywords, doc_QsciLexerCPP_keywords);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_description, "QsciLexerCPP.description(int) -> QString");

extern "C" {static PyObject *meth_QsciLexerCPP_description(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_description(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            QString*sipRes;

            sipRes = new QString((sipSelfWasArg ? sipCpp->QsciLexerCPP::description(a0) : sipCpp->description(a0)));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_description, doc_QsciLexerCPP_description);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_wordCharacters, "QsciLexerCPP.wordCharacters() -> str");

extern "C" {static PyObject *meth_QsciLexerCPP_wordCharacters(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_wordCharacters(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            const char*sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerCPP::wordCharacters() : sipCpp->wordCharacters());

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_wordCharacters, doc_QsciLexerCPP_wordCharacters);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_refreshProperties, "QsciLexerCPP.refreshProperties()");

extern "C" {static PyObject *meth_QsciLexerCPP_refreshProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_refreshProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            (sipSelfWasArg ? sipCpp->QsciLexerCPP::refreshProperties() : sipCpp->refreshProperties());

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_refreshProperties, doc_QsciLexerCPP_refreshProperties);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_foldAtElse, "QsciLexerCPP.foldAtElse() -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_foldAtElse(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_foldAtElse(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->foldAtElse();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_foldAtElse, doc_QsciLexerCPP_foldAtElse);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_foldComments, "QsciLexerCPP.foldComments() -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_foldComments(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_foldComments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->foldComments();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_foldComments, doc_QsciLexerCPP_foldComments);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_foldCompact, "QsciLexerCPP.foldCompact() -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_foldCompact(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_foldCompact(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->foldCompact();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_foldCompact, doc_QsciLexerCPP_foldCompact);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_foldPreprocessor, "QsciLexerCPP.foldPreprocessor() -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_foldPreprocessor(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_foldPreprocessor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->foldPreprocessor();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_foldPreprocessor, doc_QsciLexerCPP_foldPreprocessor);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_stylePreprocessor, "QsciLexerCPP.stylePreprocessor() -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_stylePreprocessor(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_stylePreprocessor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->stylePreprocessor();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_stylePreprocessor, doc_QsciLexerCPP_stylePreprocessor);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_setDollarsAllowed, "QsciLexerCPP.setDollarsAllowed(bool)");

extern "C" {static PyObject *meth_QsciLexerCPP_setDollarsAllowed(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_setDollarsAllowed(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            sipCpp->setDollarsAllowed(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_setDollarsAllowed, doc_QsciLexerCPP_setDollarsAllowed);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_dollarsAllowed, "QsciLexerCPP.dollarsAllowed() -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_dollarsAllowed(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_dollarsAllowed(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->dollarsAllowed();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_dollarsAllowed, doc_QsciLexerCPP_dollarsAllowed);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_setHighlightTripleQuotedStrings, "QsciLexerCPP.setHighlightTripleQuotedStrings(bool)");

extern "C" {static PyObject *meth_QsciLexerCPP_setHighlightTripleQuotedStrings(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_setHighlightTripleQuotedStrings(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            sipCpp->setHighlightTripleQuotedStrings(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_setHighlightTripleQuotedStrings, doc_QsciLexerCPP_setHighlightTripleQuotedStrings);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_highlightTripleQuotedStrings, "QsciLexerCPP.highlightTripleQuotedStrings() -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_highlightTripleQuotedStrings(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_highlightTripleQuotedStrings(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->highlightTripleQuotedStrings();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_highlightTripleQuotedStrings, doc_QsciLexerCPP_highlightTripleQuotedStrings);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_setHighlightHashQuotedStrings, "QsciLexerCPP.setHighlightHashQuotedStrings(bool)");

extern "C" {static PyObject *meth_QsciLexerCPP_setHighlightHashQuotedStrings(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_setHighlightHashQuotedStrings(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            sipCpp->setHighlightHashQuotedStrings(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_setHighlightHashQuotedStrings, doc_QsciLexerCPP_setHighlightHashQuotedStrings);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_highlightHashQuotedStrings, "QsciLexerCPP.highlightHashQuotedStrings() -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_highlightHashQuotedStrings(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_highlightHashQuotedStrings(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerCPP, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->highlightHashQuotedStrings();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_highlightHashQuotedStrings, doc_QsciLexerCPP_highlightHashQuotedStrings);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_setFoldAtElse, "QsciLexerCPP.setFoldAtElse(bool)");

extern "C" {static PyObject *meth_QsciLexerCPP_setFoldAtElse(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_setFoldAtElse(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            (sipSelfWasArg ? sipCpp->QsciLexerCPP::setFoldAtElse(a0) : sipCpp->setFoldAtElse(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_setFoldAtElse, doc_QsciLexerCPP_setFoldAtElse);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_setFoldComments, "QsciLexerCPP.setFoldComments(bool)");

extern "C" {static PyObject *meth_QsciLexerCPP_setFoldComments(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_setFoldComments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            (sipSelfWasArg ? sipCpp->QsciLexerCPP::setFoldComments(a0) : sipCpp->setFoldComments(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_setFoldComments, doc_QsciLexerCPP_setFoldComments);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_setFoldCompact, "QsciLexerCPP.setFoldCompact(bool)");

extern "C" {static PyObject *meth_QsciLexerCPP_setFoldCompact(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_setFoldCompact(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            (sipSelfWasArg ? sipCpp->QsciLexerCPP::setFoldCompact(a0) : sipCpp->setFoldCompact(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_setFoldCompact, doc_QsciLexerCPP_setFoldCompact);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_setFoldPreprocessor, "QsciLexerCPP.setFoldPreprocessor(bool)");

extern "C" {static PyObject *meth_QsciLexerCPP_setFoldPreprocessor(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_setFoldPreprocessor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            (sipSelfWasArg ? sipCpp->QsciLexerCPP::setFoldPreprocessor(a0) : sipCpp->setFoldPreprocessor(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_setFoldPreprocessor, doc_QsciLexerCPP_setFoldPreprocessor);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_setStylePreprocessor, "QsciLexerCPP.setStylePreprocessor(bool)");

extern "C" {static PyObject *meth_QsciLexerCPP_setStylePreprocessor(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_setStylePreprocessor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerCPP, &sipCpp, &a0))
        {
            (sipSelfWasArg ? sipCpp->QsciLexerCPP::setStylePreprocessor(a0) : sipCpp->setStylePreprocessor(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_setStylePreprocessor, doc_QsciLexerCPP_setStylePreprocessor);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_readProperties, "QsciLexerCPP.readProperties(QSettings, QString) -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_readProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_readProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QSettings* a0;
        const QString* a1;
        int a1State = 0;
        QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ9J1", &sipSelf, sipType_QsciLexerCPP, &sipCpp, sipType_QSettings, &a0, sipType_QString,&a1, &a1State))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerCPP::readProperties(*a0,*a1) : sipCpp->readProperties(*a0,*a1));
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_readProperties, doc_QsciLexerCPP_readProperties);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerCPP_writeProperties, "QsciLexerCPP.writeProperties(QSettings, QString) -> bool");

extern "C" {static PyObject *meth_QsciLexerCPP_writeProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerCPP_writeProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QSettings* a0;
        const QString* a1;
        int a1State = 0;
        const QsciLexerCPP *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ9J1", &sipSelf, sipType_QsciLexerCPP, &sipCpp, sipType_QSettings, &a0, sipType_QString,&a1, &a1State))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerCPP::writeProperties(*a0,*a1) : sipCpp->writeProperties(*a0,*a1));
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerCPP, sipName_writeProperties, doc_QsciLexerCPP_writeProperties);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QsciLexerCPP(void *, const sipTypeDef *);}
static void *cast_QsciLexerCPP(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QsciLexerCPP)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QsciLexer)->ctd_cast((QsciLexer *)(QsciLexerCPP *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QsciLexerCPP(void *, int);}
static void release_QsciLexerCPP(void *sipCppV,int)
{
    QsciLexerCPP *sipCpp = reinterpret_cast<QsciLexerCPP *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QsciLexerCPP(sipSimpleWrapper *);}
static void dealloc_QsciLexerCPP(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQsciLexerCPP *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QsciLexerCPP(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_type_QsciLexerCPP(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QsciLexerCPP(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQsciLexerCPP *sipCpp = 0;

    {
        QObject* a0 = 0;
        bool a1 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
            sipName_caseInsensitiveKeywords,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JHb", sipType_QObject, &a0, sipOwner, &a1))
        {
            sipCpp = new sipQsciLexerCPP(a0,a1);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QsciLexerCPP[] = {{8, 255, 1}};


static PyMethodDef methods_QsciLexerCPP[] = {
    {SIP_MLNAME_CAST(sipName_defaultColor), meth_QsciLexerCPP_defaultColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_defaultColor)},
    {SIP_MLNAME_CAST(sipName_defaultEolFill), meth_QsciLexerCPP_defaultEolFill, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_defaultEolFill)},
    {SIP_MLNAME_CAST(sipName_defaultFont), meth_QsciLexerCPP_defaultFont, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_defaultFont)},
    {SIP_MLNAME_CAST(sipName_defaultPaper), meth_QsciLexerCPP_defaultPaper, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_defaultPaper)},
    {SIP_MLNAME_CAST(sipName_description), meth_QsciLexerCPP_description, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_description)},
    {SIP_MLNAME_CAST(sipName_dollarsAllowed), meth_QsciLexerCPP_dollarsAllowed, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_dollarsAllowed)},
    {SIP_MLNAME_CAST(sipName_foldAtElse), meth_QsciLexerCPP_foldAtElse, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_foldAtElse)},
    {SIP_MLNAME_CAST(sipName_foldComments), meth_QsciLexerCPP_foldComments, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_foldComments)},
    {SIP_MLNAME_CAST(sipName_foldCompact), meth_QsciLexerCPP_foldCompact, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_foldCompact)},
    {SIP_MLNAME_CAST(sipName_foldPreprocessor), meth_QsciLexerCPP_foldPreprocessor, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_foldPreprocessor)},
    {SIP_MLNAME_CAST(sipName_highlightHashQuotedStrings), meth_QsciLexerCPP_highlightHashQuotedStrings, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_highlightHashQuotedStrings)},
    {SIP_MLNAME_CAST(sipName_highlightTripleQuotedStrings), meth_QsciLexerCPP_highlightTripleQuotedStrings, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_highlightTripleQuotedStrings)},
    {SIP_MLNAME_CAST(sipName_keywords), meth_QsciLexerCPP_keywords, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_keywords)},
    {SIP_MLNAME_CAST(sipName_language), meth_QsciLexerCPP_language, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_language)},
    {SIP_MLNAME_CAST(sipName_lexer), meth_QsciLexerCPP_lexer, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_lexer)},
    {SIP_MLNAME_CAST(sipName_readProperties), meth_QsciLexerCPP_readProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_readProperties)},
    {SIP_MLNAME_CAST(sipName_refreshProperties), meth_QsciLexerCPP_refreshProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_refreshProperties)},
    {SIP_MLNAME_CAST(sipName_setDollarsAllowed), meth_QsciLexerCPP_setDollarsAllowed, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_setDollarsAllowed)},
    {SIP_MLNAME_CAST(sipName_setFoldAtElse), meth_QsciLexerCPP_setFoldAtElse, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_setFoldAtElse)},
    {SIP_MLNAME_CAST(sipName_setFoldComments), meth_QsciLexerCPP_setFoldComments, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_setFoldComments)},
    {SIP_MLNAME_CAST(sipName_setFoldCompact), meth_QsciLexerCPP_setFoldCompact, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_setFoldCompact)},
    {SIP_MLNAME_CAST(sipName_setFoldPreprocessor), meth_QsciLexerCPP_setFoldPreprocessor, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_setFoldPreprocessor)},
    {SIP_MLNAME_CAST(sipName_setHighlightHashQuotedStrings), meth_QsciLexerCPP_setHighlightHashQuotedStrings, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_setHighlightHashQuotedStrings)},
    {SIP_MLNAME_CAST(sipName_setHighlightTripleQuotedStrings), meth_QsciLexerCPP_setHighlightTripleQuotedStrings, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_setHighlightTripleQuotedStrings)},
    {SIP_MLNAME_CAST(sipName_setStylePreprocessor), meth_QsciLexerCPP_setStylePreprocessor, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_setStylePreprocessor)},
    {SIP_MLNAME_CAST(sipName_stylePreprocessor), meth_QsciLexerCPP_stylePreprocessor, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_stylePreprocessor)},
    {SIP_MLNAME_CAST(sipName_wordCharacters), meth_QsciLexerCPP_wordCharacters, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_wordCharacters)},
    {SIP_MLNAME_CAST(sipName_writeProperties), meth_QsciLexerCPP_writeProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerCPP_writeProperties)}
};

static sipEnumMemberDef enummembers_QsciLexerCPP[] = {
    {sipName_Comment, static_cast<int>(QsciLexerCPP::Comment), -1},
    {sipName_CommentDoc, static_cast<int>(QsciLexerCPP::CommentDoc), -1},
    {sipName_CommentDocKeyword, static_cast<int>(QsciLexerCPP::CommentDocKeyword), -1},
    {sipName_CommentDocKeywordError, static_cast<int>(QsciLexerCPP::CommentDocKeywordError), -1},
    {sipName_CommentLine, static_cast<int>(QsciLexerCPP::CommentLine), -1},
    {sipName_CommentLineDoc, static_cast<int>(QsciLexerCPP::CommentLineDoc), -1},
    {sipName_Default, static_cast<int>(QsciLexerCPP::Default), -1},
    {sipName_DoubleQuotedString, static_cast<int>(QsciLexerCPP::DoubleQuotedString), -1},
    {sipName_GlobalClass, static_cast<int>(QsciLexerCPP::GlobalClass), -1},
    {sipName_HashQuotedString, static_cast<int>(QsciLexerCPP::HashQuotedString), -1},
    {sipName_Identifier, static_cast<int>(QsciLexerCPP::Identifier), -1},
    {sipName_InactiveComment, static_cast<int>(QsciLexerCPP::InactiveComment), -1},
    {sipName_InactiveCommentDoc, static_cast<int>(QsciLexerCPP::InactiveCommentDoc), -1},
    {sipName_InactiveCommentDocKeyword, static_cast<int>(QsciLexerCPP::InactiveCommentDocKeyword), -1},
    {sipName_InactiveCommentDocKeywordError, static_cast<int>(QsciLexerCPP::InactiveCommentDocKeywordError), -1},
    {sipName_InactiveCommentLine, static_cast<int>(QsciLexerCPP::InactiveCommentLine), -1},
    {sipName_InactiveCommentLineDoc, static_cast<int>(QsciLexerCPP::InactiveCommentLineDoc), -1},
    {sipName_InactiveDefault, static_cast<int>(QsciLexerCPP::InactiveDefault), -1},
    {sipName_InactiveDoubleQuotedString, static_cast<int>(QsciLexerCPP::InactiveDoubleQuotedString), -1},
    {sipName_InactiveGlobalClass, static_cast<int>(QsciLexerCPP::InactiveGlobalClass), -1},
    {sipName_InactiveHashQuotedString, static_cast<int>(QsciLexerCPP::InactiveHashQuotedString), -1},
    {sipName_InactiveIdentifier, static_cast<int>(QsciLexerCPP::InactiveIdentifier), -1},
    {sipName_InactiveKeyword, static_cast<int>(QsciLexerCPP::InactiveKeyword), -1},
    {sipName_InactiveKeywordSet2, static_cast<int>(QsciLexerCPP::InactiveKeywordSet2), -1},
    {sipName_InactiveNumber, static_cast<int>(QsciLexerCPP::InactiveNumber), -1},
    {sipName_InactiveOperator, static_cast<int>(QsciLexerCPP::InactiveOperator), -1},
    {sipName_InactivePreProcessor, static_cast<int>(QsciLexerCPP::InactivePreProcessor), -1},
    {sipName_InactivePreProcessorComment, static_cast<int>(QsciLexerCPP::InactivePreProcessorComment), -1},
    {sipName_InactivePreProcessorCommentLineDoc, static_cast<int>(QsciLexerCPP::InactivePreProcessorCommentLineDoc), -1},
    {sipName_InactiveRawString, static_cast<int>(QsciLexerCPP::InactiveRawString), -1},
    {sipName_InactiveRegex, static_cast<int>(QsciLexerCPP::InactiveRegex), -1},
    {sipName_InactiveSingleQuotedString, static_cast<int>(QsciLexerCPP::InactiveSingleQuotedString), -1},
    {sipName_InactiveTripleQuotedVerbatimString, static_cast<int>(QsciLexerCPP::InactiveTripleQuotedVerbatimString), -1},
    {sipName_InactiveUUID, static_cast<int>(QsciLexerCPP::InactiveUUID), -1},
    {sipName_InactiveUnclosedString, static_cast<int>(QsciLexerCPP::InactiveUnclosedString), -1},
    {sipName_InactiveVerbatimString, static_cast<int>(QsciLexerCPP::InactiveVerbatimString), -1},
    {sipName_Keyword, static_cast<int>(QsciLexerCPP::Keyword), -1},
    {sipName_KeywordSet2, static_cast<int>(QsciLexerCPP::KeywordSet2), -1},
    {sipName_Number, static_cast<int>(QsciLexerCPP::Number), -1},
    {sipName_Operator, static_cast<int>(QsciLexerCPP::Operator), -1},
    {sipName_PreProcessor, static_cast<int>(QsciLexerCPP::PreProcessor), -1},
    {sipName_PreProcessorComment, static_cast<int>(QsciLexerCPP::PreProcessorComment), -1},
    {sipName_PreProcessorCommentLineDoc, static_cast<int>(QsciLexerCPP::PreProcessorCommentLineDoc), -1},
    {sipName_RawString, static_cast<int>(QsciLexerCPP::RawString), -1},
    {sipName_Regex, static_cast<int>(QsciLexerCPP::Regex), -1},
    {sipName_SingleQuotedString, static_cast<int>(QsciLexerCPP::SingleQuotedString), -1},
    {sipName_TripleQuotedVerbatimString, static_cast<int>(QsciLexerCPP::TripleQuotedVerbatimString), -1},
    {sipName_UUID, static_cast<int>(QsciLexerCPP::UUID), -1},
    {sipName_UnclosedString, static_cast<int>(QsciLexerCPP::UnclosedString), -1},
    {sipName_VerbatimString, static_cast<int>(QsciLexerCPP::VerbatimString), -1},
};

PyDoc_STRVAR(doc_QsciLexerCPP, "\1QsciLexerCPP(QObject parent=None, bool caseInsensitiveKeywords=False)");


pyqt4ClassTypeDef sipTypeDef_Qsci_QsciLexerCPP = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QsciLexerCPP,
        {0}
    },
    {
        sipNameNr_QsciLexerCPP,
        {0, 0, 1},
        28, methods_QsciLexerCPP,
        50, enummembers_QsciLexerCPP,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QsciLexerCPP,
    -1,
    -1,
    supers_QsciLexerCPP,
    0,
    init_type_QsciLexerCPP,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QsciLexerCPP,
    0,
    0,
    0,
    release_QsciLexerCPP,
    cast_QsciLexerCPP,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QsciLexerCPP::staticMetaObject,
    0,
    0
};
